### ISSUE TITLE
Not working in windows

### ISSUE THREAD

**Issue by cuom1999** [bicsi/testutil#2]
Here is the log, seems like an encoding error. (Windows 10)

```
$ cprep generate
Discovered files:
 - gen.cpp  (generator)
 - sol.cpp  (solution)
 - tests.sh (tests)

Compiling all files...
 - gen.cpp Traceback (most recent call last):
  File "d:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Miniconda3\Scripts\cprep.exe\__main__.py", line 7, in <module>
  File "d:\programdata\miniconda3\lib\site-packages\cprep_cli\__main__.py", line 54, in main
    args.run(cfg, args)
  File "d:\programdata\miniconda3\lib\site-packages\cprep_cli\commands\generate.py", line 15, in run
    pipelines.compile_files(files, cfg)
  File "d:\programdata\miniconda3\lib\site-packages\cprep_cli\pipelines.py", line 74, in compile_files
    print(line)
  File "d:\programdata\miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 5: character maps to <undefined>
```

**Comment by bicsi** [comment]
Which terminal are you using?

**Comment by cuom1999** [comment]
I use cmd in windows.

**Comment by bicsi** [comment]
Could you try installing the latest version by rinning `pip install --upgrade cprep`? I might have fixed it, but I can’t test it, as it doesn’t happen on my machine.

**Comment by cuom1999** [comment]
It's working now. Thanks!
